project:
  type: website
  output-dir: docs

website:
  title: "R Code Website"
  navbar:
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



