project:
  type: website
  output-dir: docs


website:
  title: "R Code Website"
  site-url: www.inqs.info/rcode
  navbar:      # no page links on the left
    right:
      - text: "Manuals"
        menu:
          - text: "Categorical Statistics"
            href: https://inqs.info/rcode/cat_stats
          - text: "Numerical Statistics"
            href: https://inqs.info/rcode/num_stats
          - text: "Linear Regression"
            href: https://inqs.info/rcode/regression
          - text: "Logistic Regression"
            href: https://inqs.info/rcode/logistic
  search:
    location: navbar
format:
  html:
    theme:
      light: theme.scss
      dark: dark.scss


