project:
  type: website
  output-dir: docs

website:
  title: "R Code Website"
  navbar:
    left: []        # no page links on the left
    right: []       # no page links on the right
  search:
    location: navbar
format:
  html:
    theme:
      light: theme.scss
      dark: dark.scss


