project:
  type: website
  output-dir: docs


website:
  title: "R Code Website"
  site-url: www.inqs.info/rcode
  navbar:      # no page links on the left
    right:
      - text: "Manuals"
        menu:
          - posts/cat_stats.qmd
          - posts/num_stats.qmd
          - posts/regression.qmd
          - posts/logistic.qmd
  search:
    location: navbar
format:
  html:
    theme:
      light: theme.scss
      dark: dark.scss


